#!/bin/bash
sort -u <(expac '%n') <(expac '%E' -l '\n') > /tmp/march-old
grep -v -h ^# /usr/share/march/{packages,extra}.list | sort -u > /tmp/march-new
while true; do
	sort -u /tmp/march-new <(expac '%E' -l '\n' $(</tmp/march-new)) > /tmp/march-new2
	if cmp -s /tmp/march-new /tmp/march-new2; then
		rm /tmp/march-new2
		break
	fi
	cp /tmp/march-new2 /tmp/march-new
done

echo '[remove]'
comm -23 /tmp/march-old /tmp/march-new

echo

echo '[add]'
comm -13 /tmp/march-old /tmp/march-new

rm /tmp/march-{old,new}
