#!/bin/bash
[[ $EUID != 0 ]] && exit 1
pacman -Qqe | sort > /tmp/march-old
cat /usr/share/march/{packages,extra}.list | grep -v ^# | sort > /tmp/march-new

# to be removed
cat <<EOF
Remove
======
$(comm -23 /tmp/march-old /tmp/march-new)
EOF

# to be added
pacman -Sy $(comm -13 /tmp/march-old /tmp/march-new)

rm /tmp/march-{old,new}
